# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17196c929a46c32beb8c87cf87c0a47acb8c39df5e7288cd9a2f99a3a9ccb263acc615e72db8a96dc5c2a4a85aaa2ffc93c556c9a6ad731890159d2e7da175c8

test:
  secret_key_base: 81a409679f59f5c3ac7c24276ba23a988af415a1271ba1f5815820318255032afdfba37815c7273d71a4a14abf2fc9dbd437b40d7c5c6a094b2f087b180f7015

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
